defaults: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: Solitude
  password: 
  host: localhost

development:
  <<: *defaults
  database: me_app_development

test:
  <<: *defaults
  database: me_app_test
